photoBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView)
from django.urls import path
import authentication.views
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('', LoginView.as_view(
        template_name = 'authentication/login.html',
        redirect_authenticated_user = True
        ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html'
        ), name='password_change'),
    path('change-password-done/', PasswordChangeDoneView.as_view(
        template_name='authentication/password_change_done.html'
        ), name='password_change_done'),
    path('home/', blog.views.home_page, name='home'),
    path('photo/upload/', blog.views.photo_upload, name='photo_upload'),
    path('profile-photo/upload/', authentication.views.profile_photo_upload, name='profile_photo_upload'),
    path('blog/create/', blog.views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:post_id>/', blog.views.post_view, name='post_view'),
    path('blog/<int:post_id>/edit/', blog.views.edit_post, name='edit_post'),
    path('photo/multiple-upload/', blog.views.multiple_photo_upload, name='multiple_photo_upload'),
    path('follow_users/', blog.views.follow_users, name='follow_users'),
    path('photo_feed/', blog.views.photo_feed, name='photo_feed'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models

from PIL import Image

class Photo(models.Model):

    def __str__(self):
        return f'{self.caption}'
    
    image = models.ImageField()
    caption = models.CharField(max_length=150, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    IMAGE_MAX_SIZE = (800,800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

class Blog(models.Model):

    def __str__(self):
        return f'{self.title}'
    
    Photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=150)
    Content = models.CharField(max_length=5000)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')

    def _get_word_count(self):
        return len(self.Content.split(' '))

    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)

class BlogContributor(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('blog', 'contributor')

templates/base.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'app.css' %}">
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<title>PhotoBlog</title>
	</head>
	<body id="bloc_page">
		<div class="sidebar">
            <h1>FotoBlog</h1>
            {% if user.is_authenticated %}
                <p>Salut, {{ user }} !</p>
                {% if user.profile_photo %}
                    <img class="avatar" src={{ user.profile_photo.url }}>
                {% else %}
                    <img class="avatar" src="{% static 'media/default_profile_photo.png' %}">
                {% endif %}
                <p><a href="{% url 'home' %}">Accueil</a></p>
                <p><a href="{% url 'photo_feed' %}">Flux de photos</a></p>
                {% if perms.blog.add_blog %}
                    <p><a href="{% url 'blog_create' %}">Écrire un post</a></p>
                {% endif %}
                {% if perms.blog.add_photo %}
                    <p><a href="{% url 'photo_upload' %}">Téléverser une photo</a></p>
                    <p><a href="{% url 'multiple_photo_upload' %}">Téléverser plusieurs photos</a></p>
                {% endif %}
                <p><a href="{% url 'follow_users' %}">Suivres des utilisateurs</a></p>
                <p><a href="{% url 'profile_photo_upload' %}">Changer la photo de profil</a></p>
                <p><a href="{% url 'password_change' %}">Changer le mot de passe</a></p>
                <p><a href="{% url 'logout' %}">Se déconnecter</a></p>
            {% endif %}
        </div>

		<div class="my-5 main">
		    {% block content %}{% endblock %}
		</div>
		</body>
	</html>